export const COVID_19 = "https://gateway.pinata.cloud/ipfs/QmcEASf8BoztaFUKA68dmRQrECUakadmjEBwZXKQGroMaS"
export const DRIED_BLOOD = "https://gateway.pinata.cloud/ipfs/QmPZ5Ew7dZbLpjfJxLTgmYWEUycHVsLLDxaRD5RwPn2oQs"
export const URINE_COLLECTION = "https://gateway.pinata.cloud/ipfs/Qmcei89XiFjZuU5dEnJ9XkDB9JHhisaY5cuz2Ym66mMRhc"
export const FECAL_COLLECTION = "https://gateway.pinata.cloud/ipfs/QmaHSSVsLZarX4EJbhWdNHjTnehpFMjh68X4mv1EiFSEaB"
export const SALIVA_COLLECTION = "https://gateway.pinata.cloud/ipfs/QmPZ5Ew7dZbLpjfJxLTgmYWEUycHVsLLDxaRD5RwPn2oQs"
export const BUCCAL_COLLECTION = "https://gateway.pinata.cloud/ipfs/QmcSZrMdraU2RKXhXbGBTZ8p1CnQibixeqDtc6Kwun7Qd2"
